from lambdas.constants import (
    EVALUATION_NOTE_DEFAULT_OUTPUT_DIR as DEFAULT_OUTPUT_DIR,
    EVALUATION_NOTE_OUTPUT_DIR_ENV_KEY,
)

OUTPUT_FILE_PREFIX = "evaluation_notes"
OUTPUT_TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"
