from lambdas.constants import (
    EMBEDDING_VECTOR_DIMS,
    ES_FIELD_DEVICE_ID,
    ES_FIELD_DEVICE_TYPE,
    ES_FIELD_EVALUATION_DATE,
    ES_FIELD_FACILITY_ID,
    ES_FIELD_FINDINGS_EMBEDDING,
    ES_FIELD_FINDINGS_TEXT,
    ES_FIELD_LOCATION,
    ES_FIELD_MANUFACTURER,
    ES_FIELD_REMEDIATION_EMBEDDING,
    ES_FIELD_REMEDIATION_TEXT,
    ES_MAPPING_KEY_DIMS,
    ES_MAPPING_KEY_INDEX,
    ES_MAPPING_KEY_MAPPINGS,
    ES_MAPPING_KEY_PROPERTIES,
    ES_MAPPING_KEY_SIMILARITY,
    ES_MAPPING_KEY_TYPE,
    ES_MAPPING_SIMILARITY_COSINE,
    ES_MAPPING_TYPE_DATE,
    ES_MAPPING_TYPE_DENSE_VECTOR,
    ES_MAPPING_TYPE_KEYWORD,
    ES_MAPPING_TYPE_TEXT,
)

EVALUATION_NOTES_INDEX_MAPPINGS = {
    ES_MAPPING_KEY_MAPPINGS: {
        ES_MAPPING_KEY_PROPERTIES: {
            ES_FIELD_FINDINGS_TEXT: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_TEXT},
            ES_FIELD_REMEDIATION_TEXT: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_TEXT},
            ES_FIELD_FINDINGS_EMBEDDING: {
                ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_DENSE_VECTOR,
                ES_MAPPING_KEY_DIMS: EMBEDDING_VECTOR_DIMS,
                ES_MAPPING_KEY_INDEX: True,
                ES_MAPPING_KEY_SIMILARITY: ES_MAPPING_SIMILARITY_COSINE,
            },
            ES_FIELD_REMEDIATION_EMBEDDING: {
                ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_DENSE_VECTOR,
                ES_MAPPING_KEY_DIMS: EMBEDDING_VECTOR_DIMS,
                ES_MAPPING_KEY_INDEX: True,
                ES_MAPPING_KEY_SIMILARITY: ES_MAPPING_SIMILARITY_COSINE,
            },
            ES_FIELD_DEVICE_TYPE: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_KEYWORD},
            ES_FIELD_MANUFACTURER: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_KEYWORD},
            ES_FIELD_DEVICE_ID: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_KEYWORD},
            ES_FIELD_FACILITY_ID: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_KEYWORD},
            ES_FIELD_LOCATION: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_KEYWORD},
            ES_FIELD_EVALUATION_DATE: {ES_MAPPING_KEY_TYPE: ES_MAPPING_TYPE_DATE},
        }
    }
}
